spring:
  application:
    name: financial-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

