name: esteira-ci-dev

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21 ]
    steps:
      - name: Checa o git
        uses: actions/checkout@v2

      - name: Faz o set JDK Java
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build Maven
        run: mvn clean install

      - name: Roda os testes da aplicação
        run: mvn test

      - name: Cria uma release/tag no gitHub
        id: release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (VERSAO) Publicar release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.release.outputs.id }}

      - name: Upload jar na release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./target/financial-api.jar
          asset_name: financial-api.jar
          asset_content_type: application/jar